- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Ensures cache is valid for an hour

    - name: Install Docker
      apt:
        name: docker.io
        state: present  # Ensures Docker is installed

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes  # Ensures Docker starts on boot

    - name: Deploy Docker Container
      docker_container:
        name: healthcare-container
        image: kartseka1/healthcare-karthi:1
        state: started
        restart_policy: always
        ports:
          - "8086:8082"  # Mapping ports 8087 on host to 8082 in container
