apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        name: healthcare
    spec:
      containers:
        - name: simple-container
          image: kartseka1/healthcare-karthi:1
          ports:
            - containerPort: 8082

  ---
apiVersion: v1
kind: Service 
metadata:
  name: healthcare
spec:
   selector:
       app: healthcare
      type: NodePort
      ports:
         - port: 80
         targetPort: 8082
         nodeport: 30007
       
