apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare  # Ensure the label here matches the selector in the Service
  template:
    metadata:
      labels:
        app: healthcare  # Ensure this matches the selector in the Service
    spec:
      containers:
        - name: healthcare-container
          image: kartseka1/healthcare-karthi:1
          ports:
            - containerPort: 8082  # Ensure the application is listening on this port

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  selector:
    app: healthcare  # Ensure this matches the labels in the Deployment
  type: NodePort
  ports:
    - port: 80         # External port exposed by the Service
      targetPort: 8082  # The port on the container to which the traffic will be directed
      nodePort: 30007   # The port on the node which will be exposed
